### ISSUE TITLE
Further increased chapter splitting speed

### ISSUE THREAD

**Issue by Nicko98** [KrumpetPirate/AAXtoMP3#142]
While working on my the compression levels I found a way to further increase the chapter splitting speed (depending on the codec by a factor of 3-8 faster again!):

One could just set up the ffmpeg command which splits the chapters off with `-acodec copy` instead of `-acodec "${codec}"` since we already converted it in the first step.

The problem is, that this copies all the metadata from the big single file (including track duration so that in the end every track has the duration of the whole audiobook as duration for that chapter in the metadata) if not explicitely set correctly.

If someone could tell me, how i can see all the metadata so that i can look, which ones I have to correct in the splitting part, I'd implement this tomorrow.

**Comment by Nicko98** [comment]
I think I'll wait until fabh2o is done with his commits.

**Comment by fabh2o** [comment]
> I think I'll wait until fabh2o is done with his commits.

If the last pull request gets merged I think I'm done with the metadata. About how to see the actual metadata of the files, take a look at `exiftool`, `ffprobe` and `mediainfo`. `ffmpeg` can export (and import) metadata from a file, [(documentation)](http://ffmpeg.org/ffmpeg-formats.html#Metadata-1), you might want to look into it. One last place to look for metadata is the temporary metadata file, it gets printed by the script if the debug flag is set

**Comment by Nicko98** [comment]
Ok, I'll wait for that.
I'll have a look and will implement my changes this weekend.
Thanks for the hints!

**Comment by KrumpetPirate** [comment]
Merged the request by @fabh2o. Wouldn't want to be the blocker!

**Comment by Nicko98** [comment]
Hey guys,
I'm a little stuck on this, maybe you can help me out.
This is the ffmpeg command to split of the chapters, but a little shortned to exclude error sources:

`ffmpeg -ss "${chapter_start%?}"  -to "${chapter_end}"  -i "${single_file}" -acodec "${codec}" -f ${container} "${chapter_file}"`
This produces a perfectly working chapter file just as expacted.

`ffmpeg -ss "${chapter_start%?}"  -to "${chapter_end}"  -i "${single_file}" -acodec copy -f ${container} "${chapter_file}"`
This produces a perfectly working file of the same length as the command above, but the file shows the up the duration of the single_file instead of the chapter length.
Contradicting my first guess this doesn't seem to be a metadata issue.

Any guesses? We could just stay with the first command, but since the second one speeds up the chapter splitting approximately by a factor of 5 compared to the first one we should maybe sort this out...

**Comment by fabh2o** [comment]
From my test (https://github.com/fabh2o/AAXtoMP3/tree/faster-chapter-splitting) it seems like that the output chapters files are perfect: they have the correct length (in the metadata and the one reported by a player).
Maybe it was a `ffmpeg` bug that has been fixed, and you have an older version. Mine report `ffmpeg version n4.3.1`

**Comment by Nicko98** [comment]
Interesting. I have version 4.2.4-1ubuntu0.1 (the latest from ubuntu sources). I'll get the latest version this evening and try again. Thanks.

**Comment by Nicko98** [comment]
ffmpeg version N-100999-gbd52267 (compiled following this guide: https://trac.ffmpeg.org/wiki/CompilationGuide/Ubuntu) has the same issue.

**Comment by fabh2o** [comment]
What code did you try? Can you try my [branch](https://github.com/fabh2o/AAXtoMP3/tree/faster-chapter-splitting)?
If you run `exiftool -Duration *.mp3` or `mediainfo --Inform="General;%Duration%" *.mp3`, do all chapters show the same value?

**Comment by Nicko98** [comment]
I did and still the same. Now I use the Snap version (n4.3.1). And yes, with `exiftool -Duration *.mp3` and `mediainfo --Inform="General;%Duration%" *.mp3` all chapters show the same value.

**Comment by Nicko98** [comment]
Now I've taken the source code from http://ffmpeg.org/download.html compiled it and still have the same problem.

**Comment by Nicko98** [comment]
fabh2o what system do you run this on?
I'm working with an MacBook Air (13" 2010, lowest specs), but with Ubuntu instead of MacOS (was getting very, very slow).

**Comment by fabh2o** [comment]
Updated ArchLinux with `5.10.13-arch1-2` kernel, tested with [this version](https://github.com/fabh2o/AAXtoMP3/tree/faster-chapter-splitting) (the main [difference](https://github.com/KrumpetPirate/AAXtoMP3/compare/master...fabh2o:faster-chapter-splitting) from the current upstream is the `-codec:a copy` flag and the verbose ffmpeg).

Mediainfo, exiftool and ffprobe report the same (correct) length of each file (chapter).

A log file from the script, plus the output of exiftool and ffprobe on the output files
[LOG.log](https://github.com/KrumpetPirate/AAXtoMP3/files/5943335/LOG.log)

**Comment by Nicko98** [comment]
Unexpectedly today this works for mp3 and ogg. But for flac the problem remains. Could you try this with flac too?
If you can reproduce this issue, I'd assume this is a bug in ffmpegs flac codec. I'd then report this and propose to implement a double implementation until this issue is sorted out: code flac for flac and codec copy else. I'd then open a pull request tomorrow with this implemented.

**Comment by Nicko98** [comment]
I just implemented it [as mentioned above](https://github.com/Nicko98/AAXtoMP3/tree/faster-chapter-splitting).

**Comment by fabh2o** [comment]
I can confirm, all codecs except flac report the correct length. I think it's a bug in ffmpeg.
Does it makes sense to set the compression_level in both the main ffmpeg transcode **and** the splitting loop?
Since you removed the id3_version_param variable, you should also delete it in the `debug_vars "Chapter Variables:"...` line

**Comment by Nicko98** [comment]
It’s even neccessary since it would otherwise change the compression level to 5 (default) while splitting regardless of what Level was Set for the initial conversion. Of course I could hardcode it to use compression level 0 for the first step, which would be a little bit faster, but since 5 is nearly as fast as 0 this isn‘t much of an benefit and it would be confusing for someone else to reverse these changes, when a future ffmpeg version fixed this issue.

Regarding the debug_vars you are right. I‘ll change that!
